map ctrl+shift+v paste_from_clipboard
map ctrl+shift+c copy_to_clipboard
font_family      JetBrains Mono Regular
bold_font        JetBrains Mono Bold
italic_font      JetBrains Mono Italic
bold_italic_font JetBrains Mono Bold Italic

font_size 11.0

# Жесткий фикс геометрии (запрещает буквам уезжать)
adjust_line_height  100%
adjust_column_width 100%
spacing 0


# Отключить CSI u protocol

# Маппинг Ctrl+Shift+C/V явно чтобы не уходило в CSI u
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
allow_remote_control no
shell_integration disabled

# --- Прозрачность окна терминала ---
# Значение от 0.0 (полностью прозрачный) до 1.0 (плотный цвет)
background_opacity 0.8

# --- Кастомизация ---
# Отключает раздражающий системный писк при ошибках
blur 
enable_audio_bell no

# Цвета фона и текста (если не используешь готовые темы)
background #1e1f22
foreground #cdd6f4
confirm_os_window_close 0

selection_background #1e1f22
selection_foreground #ffffff
